# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "salt")
Ingredient.create(name: "pepper")
Ingredient.create(name: "sugar")
Ingredient.create(name: "oil")
Ingredient.create(name: "flour")
Ingredient.create(name: "apple")
Ingredient.create(name: "cointreau")
Ingredient.create(name: "cherry")
Ingredient.create(name: "rose")
Ingredient.create(name: "orange")
Ingredient.create(name: "chocolat")
Ingredient.create(name: "black pepper")
Ingredient.create(name: "crabe")
Ingredient.create(name: "fish")
Ingredient.create(name: "garlic")
Ingredient.create(name: "chicken")
Ingredient.create(name: "pepper bells")
Ingredient.create(name: "oignon")
Ingredient.create(name: "fromage")
Ingredient.create(name: "champagne")
Ingredient.create(name: "gin")
Ingredient.create(name: "vodka")
Ingredient.create(name: "rhum")
Ingredient.create(name: "whisky")
Ingredient.create(name: "get 27")
Ingredient.create(name: "beer")
Ingredient.create(name: "cactus")
Ingredient.create(name: "lemon")
